
package View;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JPanel;
import java.sql.*;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import java.awt.BorderLayout;
import javax.swing.JLabel;


public class AdminDashboard extends javax.swing.JFrame {

    public AdminDashboard() {
        initComponents();
        
// Set normal and hover colors
java.awt.Color normalColor = new java.awt.Color(255, 243, 224);
java.awt.Color hoverColor = new java.awt.Color(255, 230, 200);

// Apply hover effect to all buttons
addHoverEffect(DashboardButton, normalColor, hoverColor);
addHoverEffect(OrderButton, normalColor, hoverColor);
addHoverEffect(EmployeeButton, normalColor, hoverColor);
addHoverEffect(LogoutButton, normalColor, hoverColor);
addHoverEffect(RevenuePanel, normalColor, hoverColor);
addHoverEffect(OrderPanel, normalColor, hoverColor);
addHoverEffect(EmployeePanel, normalColor, hoverColor);
addHoverEffect(Review1, normalColor, hoverColor);
addHoverEffect(Review2, normalColor, hoverColor);
addHoverEffect(Review3, normalColor, hoverColor);


    }
    private void addHoverEffect(javax.swing.JButton button, java.awt.Color normalColor, java.awt.Color hoverColor) {
    button.setOpaque(true);
    button.setBorderPainted(false);
    button.setFocusPainted(false);
    button.setBackground(normalColor);

    button.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            button.setBackground(hoverColor);
        }
        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) {
            button.setBackground(normalColor);
        }
    });
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanel = new javax.swing.JPanel();
        Logo1 = new javax.swing.JLabel();
        DashboardButton = new javax.swing.JButton();
        OrderButton = new javax.swing.JButton();
        EmployeeButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        Slogan = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TopBarPanel = new javax.swing.JPanel();
        Logo2 = new javax.swing.JLabel();
        RevenueText = new javax.swing.JLabel();
        MinimizeButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        RefreshButton = new javax.swing.JButton();
        DashboardCenterPanel = new javax.swing.JPanel();
        RevenuePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        OrderPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        EmployeePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ReviewPanel = new javax.swing.JPanel();
        Review3 = new javax.swing.JPanel();
        Review = new javax.swing.JLabel();
        CustomerReview3 = new javax.swing.JLabel();
        Review1 = new javax.swing.JPanel();
        Customer1 = new javax.swing.JLabel();
        CustomerReview1 = new javax.swing.JLabel();
        Review2 = new javax.swing.JPanel();
        Customer2 = new javax.swing.JLabel();
        CustomerReview2 = new javax.swing.JLabel();
        Customer3 = new javax.swing.JLabel();
        revenueChartPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 243, 224));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        SidePanel.setBackground(new java.awt.Color(255, 243, 224));
        SidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SidePanel.setLayout(null);

        Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Screenshot_2025-05-22_222007-removebg-preview (1).png"))); // NOI18N
        Logo1.setText("jLabel1");
        SidePanel.add(Logo1);
        Logo1.setBounds(30, 10, 136, 110);

        DashboardButton.setBackground(new java.awt.Color(255, 243, 224));
        DashboardButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DashboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dashboard.png"))); // NOI18N
        DashboardButton.setText("Dashboard");
        DashboardButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DashboardButton.setIconTextGap(10);
        SidePanel.add(DashboardButton);
        DashboardButton.setBounds(20, 190, 160, 40);

        OrderButton.setBackground(new java.awt.Color(255, 243, 224));
        OrderButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OrderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order.png"))); // NOI18N
        OrderButton.setText("Order");
        OrderButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OrderButton.setIconTextGap(10);
        SidePanel.add(OrderButton);
        OrderButton.setBounds(20, 240, 160, 40);

        EmployeeButton.setBackground(new java.awt.Color(255, 243, 224));
        EmployeeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmployeeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/employee.png"))); // NOI18N
        EmployeeButton.setText("Employee");
        EmployeeButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EmployeeButton.setIconTextGap(10);
        EmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeButtonActionPerformed(evt);
            }
        });
        SidePanel.add(EmployeeButton);
        EmployeeButton.setBounds(20, 290, 160, 40);

        LogoutButton.setBackground(new java.awt.Color(255, 243, 224));
        LogoutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogoutButton.setIconTextGap(10);
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        SidePanel.add(LogoutButton);
        LogoutButton.setBounds(20, 540, 160, 40);

        Slogan.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        Slogan.setText("7 people serving since 11 AM");
        Slogan.setToolTipText("");
        SidePanel.add(Slogan);
        Slogan.setBounds(10, 110, 180, 20);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        SidePanel.add(jSeparator1);
        jSeparator1.setBounds(0, 130, 200, 3);

        getContentPane().add(SidePanel);
        SidePanel.setBounds(0, 0, 200, 600);

        TopBarPanel.setBackground(new java.awt.Color(255, 243, 224));
        TopBarPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TopBarPanel.setLayout(null);

        Logo2.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        Logo2.setText("7 ~ 11");
        TopBarPanel.add(Logo2);
        Logo2.setBounds(10, 30, 130, 40);

        RevenueText.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        RevenueText.setText("Overall revenue illustration of last 7 days");
        TopBarPanel.add(RevenueText);
        RevenueText.setBounds(10, 80, 300, 20);

        MinimizeButton.setBackground(new java.awt.Color(255, 243, 224));
        MinimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize-sign.png"))); // NOI18N
        MinimizeButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        MinimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizeButtonMouseExited(evt);
            }
        });
        MinimizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeButtonActionPerformed(evt);
            }
        });
        TopBarPanel.add(MinimizeButton);
        MinimizeButton.setBounds(740, 10, 20, 25);

        ExitButton.setBackground(new java.awt.Color(255, 243, 224));
        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reject.png"))); // NOI18N
        ExitButton.setText("jButton2");
        ExitButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitButtonMouseExited(evt);
            }
        });
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        TopBarPanel.add(ExitButton);
        ExitButton.setBounds(770, 10, 25, 25);

        RefreshButton.setBackground(new java.awt.Color(255, 243, 224));
        RefreshButton.setText("↻");
        RefreshButton.setBorder(null);
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });
        TopBarPanel.add(RefreshButton);
        RefreshButton.setBounds(705, 10, 30, 20);

        getContentPane().add(TopBarPanel);
        TopBarPanel.setBounds(200, 0, 800, 160);

        DashboardCenterPanel.setBackground(new java.awt.Color(253, 253, 242));
        DashboardCenterPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DashboardCenterPanel.setLayout(null);

        RevenuePanel.setBackground(new java.awt.Color(255, 243, 224));
        RevenuePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("MonthlyRevenue");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText("Rs 70000");

        javax.swing.GroupLayout RevenuePanelLayout = new javax.swing.GroupLayout(RevenuePanel);
        RevenuePanel.setLayout(RevenuePanelLayout);
        RevenuePanelLayout.setHorizontalGroup(
            RevenuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RevenuePanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(RevenuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RevenuePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(20, 20, 20))
        );
        RevenuePanelLayout.setVerticalGroup(
            RevenuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RevenuePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        DashboardCenterPanel.add(RevenuePanel);
        RevenuePanel.setBounds(40, 25, 200, 100);

        OrderPanel.setBackground(new java.awt.Color(255, 243, 224));
        OrderPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Total Orders");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setText("356");

        javax.swing.GroupLayout OrderPanelLayout = new javax.swing.GroupLayout(OrderPanel);
        OrderPanel.setLayout(OrderPanelLayout);
        OrderPanelLayout.setHorizontalGroup(
            OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderPanelLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        OrderPanelLayout.setVerticalGroup(
            OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        DashboardCenterPanel.add(OrderPanel);
        OrderPanel.setBounds(300, 25, 200, 100);

        EmployeePanel.setBackground(new java.awt.Color(255, 243, 224));
        EmployeePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("Total Employee");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel6.setText("32");

        javax.swing.GroupLayout EmployeePanelLayout = new javax.swing.GroupLayout(EmployeePanel);
        EmployeePanel.setLayout(EmployeePanelLayout);
        EmployeePanelLayout.setHorizontalGroup(
            EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeePanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        EmployeePanelLayout.setVerticalGroup(
            EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        DashboardCenterPanel.add(EmployeePanel);
        EmployeePanel.setBounds(560, 25, 200, 100);

        ReviewPanel.setBackground(new java.awt.Color(255, 243, 224));
        ReviewPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ReviewPanel.setLayout(null);

        Review3.setBackground(new java.awt.Color(229, 216, 176));

        Review.setText("Krischal Lamichhane");

        CustomerReview3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        CustomerReview3.setText("Polite Server");

        javax.swing.GroupLayout Review3Layout = new javax.swing.GroupLayout(Review3);
        Review3.setLayout(Review3Layout);
        Review3Layout.setHorizontalGroup(
            Review3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Review3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Review3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Review3Layout.createSequentialGroup()
                        .addComponent(Review)
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addComponent(CustomerReview3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Review3Layout.setVerticalGroup(
            Review3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Review3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Review)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustomerReview3)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        ReviewPanel.add(Review3);
        Review3.setBounds(10, 190, 180, 70);

        Review1.setBackground(new java.awt.Color(229, 216, 176));

        Customer1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        Customer1.setText("Salina Shrestha");

        CustomerReview1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        CustomerReview1.setText("The food here is great.");

        javax.swing.GroupLayout Review1Layout = new javax.swing.GroupLayout(Review1);
        Review1.setLayout(Review1Layout);
        Review1Layout.setHorizontalGroup(
            Review1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Review1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Review1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Review1Layout.createSequentialGroup()
                        .addComponent(Customer1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(CustomerReview1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addContainerGap())
        );
        Review1Layout.setVerticalGroup(
            Review1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Review1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Customer1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustomerReview1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        ReviewPanel.add(Review1);
        Review1.setBounds(10, 30, 180, 70);

        Review2.setBackground(new java.awt.Color(229, 216, 176));

        Customer2.setText("Alex Maharjan");

        CustomerReview2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        CustomerReview2.setText("Great Ambience.");

        javax.swing.GroupLayout Review2Layout = new javax.swing.GroupLayout(Review2);
        Review2.setLayout(Review2Layout);
        Review2Layout.setHorizontalGroup(
            Review2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Review2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Review2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Review2Layout.createSequentialGroup()
                        .addComponent(Customer2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(CustomerReview2, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addContainerGap())
        );
        Review2Layout.setVerticalGroup(
            Review2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Review2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Customer2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustomerReview2)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        ReviewPanel.add(Review2);
        Review2.setBounds(10, 110, 180, 70);

        Customer3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Customer3.setText("Recent Reviews");
        ReviewPanel.add(Customer3);
        Customer3.setBounds(50, 10, 109, 16);

        DashboardCenterPanel.add(ReviewPanel);
        ReviewPanel.setBounds(560, 160, 200, 270);

        revenueChartPanel.setLayout(new java.awt.BorderLayout());
        DashboardCenterPanel.add(revenueChartPanel);
        revenueChartPanel.setBounds(50, 160, 450, 260);

        getContentPane().add(DashboardCenterPanel);
        DashboardCenterPanel.setBounds(200, 160, 800, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void MinimizeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonMouseEntered
        // TODO add your handling code here:
        MinimizeButton.setBackground(Color.LIGHT_GRAY);
MinimizeButton.setOpaque(true);

        
    }//GEN-LAST:event_MinimizeButtonMouseEntered

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here
        System.exit(0);


    }//GEN-LAST:event_ExitButtonActionPerformed

    private void MinimizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeButtonActionPerformed
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_MinimizeButtonActionPerformed

    private void ExitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseEntered
        // TODO add your handling code here:
        ExitButton.setBackground(Color.RED);
ExitButton.setOpaque(true);

    }//GEN-LAST:event_ExitButtonMouseEntered

    private void ExitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseExited
        // TODO add your handling code here:
        ExitButton.setBackground(new Color(255, 255, 255)); // or your top bar color
ExitButton.setOpaque(false);

    }//GEN-LAST:event_ExitButtonMouseExited

    private void MinimizeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonMouseExited
        // TODO add your handling code here:
        MinimizeButton.setBackground(new Color(255, 255, 255)); // or your top bar color
MinimizeButton.setOpaque(false);

    }//GEN-LAST:event_MinimizeButtonMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadDashboardData();    
        showMonthlyRevenueChart();
        loadRecentReviews();
    }//GEN-LAST:event_formWindowOpened

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        loadDashboardData();
    }//GEN-LAST:event_RefreshButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminDashboard().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Customer1;
    private javax.swing.JLabel Customer2;
    private javax.swing.JLabel Customer3;
    private javax.swing.JLabel CustomerReview1;
    private javax.swing.JLabel CustomerReview2;
    private javax.swing.JLabel CustomerReview3;
    private javax.swing.JButton DashboardButton;
    private javax.swing.JPanel DashboardCenterPanel;
    private javax.swing.JButton EmployeeButton;
    private javax.swing.JPanel EmployeePanel;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel Logo2;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton MinimizeButton;
    private javax.swing.JButton OrderButton;
    private javax.swing.JPanel OrderPanel;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JPanel RevenuePanel;
    private javax.swing.JLabel RevenueText;
    private javax.swing.JLabel Review;
    private javax.swing.JPanel Review1;
    private javax.swing.JPanel Review2;
    private javax.swing.JPanel Review3;
    private javax.swing.JPanel ReviewPanel;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JLabel Slogan;
    private javax.swing.JPanel TopBarPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel revenueChartPanel;
    // End of variables declaration//GEN-END:variables

private void addHoverEffect(javax.swing.JPanel panel, java.awt.Color normalColor, java.awt.Color hoverColor) {
    panel.setBackground(normalColor);

    panel.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            panel.setBackground(hoverColor);
        }

        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) {
            panel.setBackground(normalColor);
        }
    });
}
private void loadDashboardData() {
    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant", "root", "qwerty1234")) {

        // Monthly Revenue
        String revenueQuery = "SELECT SUM(total_amount) FROM orders WHERE MONTH(order_date) = MONTH(CURDATE())";
        try (PreparedStatement stmt = conn.prepareStatement(revenueQuery); ResultSet rs = stmt.executeQuery()) {
            if (rs.next()) {
                jLabel2.setText("Rs " + rs.getInt(1));
            }
        }

        // Total Orders
        String orderQuery = "SELECT COUNT(*) FROM orders";
        try (PreparedStatement stmt = conn.prepareStatement(orderQuery); ResultSet rs = stmt.executeQuery()) {
            if (rs.next()) {
                jLabel4.setText(String.valueOf(rs.getInt(1)));
            }
        }

        // Total Employees
        String employeeQuery = "SELECT COUNT(*) FROM employees";
        try (PreparedStatement stmt = conn.prepareStatement(employeeQuery); ResultSet rs = stmt.executeQuery()) {
            if (rs.next()) {
                jLabel6.setText(String.valueOf(rs.getInt(1)));
            }
        }

        // Recent Reviews (3 latest)
        String reviewQuery = "SELECT customer_name FROM reviews ORDER BY id DESC LIMIT 3";
        try (PreparedStatement stmt = conn.prepareStatement(reviewQuery); ResultSet rs = stmt.executeQuery()) {
            if (rs.next()) Customer1.setText(rs.getString(1));
            if (rs.next()) Customer2.setText(rs.getString(1));
            if (rs.next()) Review.setText(rs.getString(1));
        }

    } catch (SQLException e) {
        System.out.println("Failed to load dashboard data");
        e.printStackTrace();
    }
}
private void showMonthlyRevenueChart() {
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    // Sample data — replace with DB data later
    dataset.addValue(1200, "Revenue", "Jan");
    dataset.addValue(1500, "Revenue", "Feb");
    dataset.addValue(1800, "Revenue", "Mar");
    dataset.addValue(1400, "Revenue", "Apr");
    dataset.addValue(2000, "Revenue", "May");

    JFreeChart chart = ChartFactory.createBarChart(
        "Monthly Revenue", // Title
        "Month",            // X-axis Label
        "Revenue",          // Y-axis Label
        dataset,            // Dataset
        PlotOrientation.VERTICAL,
        false, true, false
    );

    ChartPanel chartPanel = new ChartPanel(chart);
    revenueChartPanel.removeAll();
    revenueChartPanel.add(chartPanel, BorderLayout.CENTER);
    revenueChartPanel.validate();
}
private void loadRecentReviews() {
    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant", "root", "qwerty1234");
        String query = "SELECT customer_name, review_text FROM reviews ORDER BY id DESC LIMIT 3";
        PreparedStatement stmt = conn.prepareStatement(query);
        ResultSet rs = stmt.executeQuery();

        JLabel[] nameLabels = { Customer1, Customer2, Customer3 };
        JLabel[] reviewLabels = { CustomerReview1, CustomerReview2, CustomerReview3 };

        int i = 0;
        while (rs.next() && i < 3) {
            nameLabels[i].setText(rs.getString("customer_name"));
            reviewLabels[i].setText(rs.getString("review_text"));
            i++;
        }

        conn.close();
    } catch (SQLException e) {
        System.out.println("Failed to load reviews");
        e.printStackTrace();
    }
}



}

