package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Lenovo1
 */
public class Bill extends javax.swing.JFrame {

    /**
     * Creates new form Bill
     */
    public Bill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Slogan1 = new javax.swing.JLabel();
        Logo1 = new javax.swing.JLabel();
        Dashboardbutton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Orderbutton = new javax.swing.JButton();
        jbill = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Logo2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        item = new javax.swing.JTable();
        CustomerNameField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        saveBillButton = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        generateBillButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Slogan2 = new javax.swing.JLabel();
        Logo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 225, 176));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 259, -1, -1));

        Slogan1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        Slogan1.setText("7 People Serving since 11 AM");
        jPanel1.add(Slogan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, 20));

        Logo1.setMaximumSize(new java.awt.Dimension(196, 197));
        Logo1.setMinimumSize(new java.awt.Dimension(196, 197));
        jPanel1.add(Logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 6, 179, 162));

        Dashboardbutton.setBackground(new java.awt.Color(255, 243, 224));
        Dashboardbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Dashboardbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dashboard.png"))); // NOI18N
        Dashboardbutton.setText("Dashboard");
        Dashboardbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Dashboardbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Dashboardbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 160, 40));

        jButton3.setBackground(new java.awt.Color(255, 243, 224));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Management");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 160, 40));

        Orderbutton.setBackground(new java.awt.Color(255, 243, 224));
        Orderbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Orderbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order.png"))); // NOI18N
        Orderbutton.setText("Order");
        Orderbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Orderbutton.setIconTextGap(10);
        Orderbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Orderbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 160, 40));

        jbill.setBackground(new java.awt.Color(255, 243, 224));
        jbill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbill.setText("Bill");
        jbill.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbillActionPerformed(evt);
            }
        });
        jPanel1.add(jbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 160, 40));

        logoutbtn.setBackground(new java.awt.Color(255, 243, 224));
        logoutbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logoutbtn.setText("Logout");
        logoutbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutbtn.setIconTextGap(10);
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        jPanel1.add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 160, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Screenshot_2025-05-22_222007-removebg-preview (1).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 136, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 200, 600));

        jPanel2.setBackground(new java.awt.Color(255, 239, 213));
        jPanel2.setPreferredSize(new java.awt.Dimension(1086, 967));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 236, -1, -1));
        jPanel2.add(Logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 0, -1, -1));

        item.setBackground(new java.awt.Color(255, 239, 213));
        item.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "", null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SN", "Items", "Qty", "Rate", "Amount", "Discount%", "Tax", "Total Price"
            }
        ));
        item.setShowGrid(true);
        jScrollPane1.setViewportView(item);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 770, 240));

        CustomerNameField.setBackground(new java.awt.Color(204, 204, 255));
        CustomerNameField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CustomerNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerNameFieldActionPerformed(evt);
            }
        });
        jPanel2.add(CustomerNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 230, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Customer name:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, -1));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 115, -1, -1));

        saveBillButton.setBackground(new java.awt.Color(204, 204, 204));
        saveBillButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveBillButton.setText("Save Bill");
        saveBillButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(saveBillButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 140, 40));

        exitbtn.setBackground(new java.awt.Color(204, 204, 204));
        exitbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitbtn.setText("Exit");
        exitbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 140, 40));

        generateBillButton.setBackground(new java.awt.Color(204, 204, 204));
        generateBillButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        generateBillButton.setText("Generate Billl");
        generateBillButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        generateBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBillButtonActionPerformed(evt);
            }
        });
        jPanel2.add(generateBillButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 140, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 800, 440));

        jPanel3.setBackground(new java.awt.Color(255, 243, 224));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Slogan2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Slogan2.setText("From Table to Total — Just for You");
        jPanel3.add(Slogan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 370, 50));

        Logo3.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        Logo3.setText("7 ~ 11");
        jPanel3.add(Logo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 800, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void OrderbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderbuttonActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void CustomerNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerNameFieldActionPerformed

    private void jbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbillActionPerformed

    private void DashboardbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DashboardbuttonActionPerformed

    private void generateBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBillButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generateBillButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CustomerNameField;
    private javax.swing.JButton Dashboardbutton;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel Logo2;
    private javax.swing.JLabel Logo3;
    private javax.swing.JButton Orderbutton;
    private javax.swing.JLabel Slogan1;
    private javax.swing.JLabel Slogan2;
    private javax.swing.JButton exitbtn;
    private javax.swing.JButton generateBillButton;
    private javax.swing.JTable item;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbill;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton saveBillButton;
    // End of variables declaration//GEN-END:variables

public void addBillListener(ActionListener listener){
saveBillButton.addActionListener(listener);
}
public void addExitListener(ActionListener listener){
exitbtn.addActionListener(listener);
}
public javax.swing.JTextField getCustomerNameField(){
    return CustomerNameField;
}
public javax.swing.JTable getBillTable() {
    return item; // replace with actual variable name
}

public void addGenerateBillListener(ActionListener listener) {
    saveBillButton.addActionListener(listener); // replace with actual button
}

public void showMessage(String message) {
    JOptionPane.showMessageDialog(this, message);/*
    }
    public void addExitListener(ActionListener listener){
    exitbtn.addActionListener(listener);*/
}
public void addLogoutListener(ActionListener listener) {
    logoutbtn.addActionListener(listener); 
}
public JButton getGenerateBillButton() {
    return saveBillButton;
}
public void addSaveBillListener(ActionListener listener) {
    saveBillButton.addActionListener(listener);
}
}
