/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.EmployeeController;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Nitro
 */
public class EmployeeDetailView extends javax.swing.JFrame {
private EmployeeController employeeController;
    /**
     * Creates new form EmployeeForm
     */

public EmployeeDetailView() {
        initComponents();
//        EmployeeController = new EmployeeController(this);
        employeeController = new EmployeeController(this);
        setVisible(true);
       
        employeeController = new EmployeeController(
    txtID, txtName, txtGender, txtStatus, txtDOBdate, txtRole, txtShift,
    txtDepartment, txtJoinedDate, txtAddress, txtEmail, txtPhoneNumber, lblProfileImage
);


btnSearch.addActionListener(e -> employeeController.loadEmployee());
btnAdd.addActionListener(e -> employeeController.saveEmployee());
btnEdit.addActionListener(e -> employeeController.updateEmployee());
btnDelete.addActionListener(e -> employeeController.deleteEmployee());
btnBrowseImage.addActionListener(e -> employeeController.chooseProfileImage());






    }

public boolean isValidDate(String dateStr) {
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    sdf.setLenient(false);
    try {
        sdf.parse(dateStr);
        return true;
    } catch (ParseException e) {
        return false;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        TopBarPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CenterPanel = new javax.swing.JPanel();
        lblProfileImage = new javax.swing.JLabel();
        NameLbl = new javax.swing.JLabel();
        IDlbl = new javax.swing.JLabel();
        GenderLbl = new javax.swing.JLabel();
        StatusLbl = new javax.swing.JLabel();
        DOBLbl = new javax.swing.JLabel();
        PersonalDetailsPanel = new javax.swing.JPanel();
        PersonalDetails = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        PhoneNo = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        JobDetailsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RoleLbl = new javax.swing.JLabel();
        WorkLbl = new javax.swing.JLabel();
        DepartmentLbl = new javax.swing.JLabel();
        JoinedLbl = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();
        txtShift = new javax.swing.JTextField();
        txtDepartment = new javax.swing.JTextField();
        txtJoinedDate = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtDOBdate = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnBrowseImage = new javax.swing.JButton();
        SidePanel2 = new javax.swing.JPanel();
        Logo3 = new javax.swing.JLabel();
        DashboardBtn = new javax.swing.JButton();
        OrderButton2 = new javax.swing.JButton();
        BillButton2 = new javax.swing.JButton();
        LogoutButton2 = new javax.swing.JButton();
        Slogan2 = new javax.swing.JLabel();
        reservationbtn1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        eventbtn1 = new javax.swing.JButton();
        reservationbtn4 = new javax.swing.JButton();
        Menubtn4 = new javax.swing.JButton();
        SidePanel3 = new javax.swing.JPanel();
        Logo4 = new javax.swing.JLabel();
        DashboardBtn1 = new javax.swing.JButton();
        LogoutButton3 = new javax.swing.JButton();
        Slogan3 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        employeebtn = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TopBarPanel.setBackground(new java.awt.Color(255, 243, 224));
        TopBarPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TopBarPanel.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Add your Member Here");
        TopBarPanel.add(jLabel3);
        jLabel3.setBounds(210, 70, 310, 50);

        jLabel4.setFont(new java.awt.Font("Jaini Purva", 3, 36)); // NOI18N
        jLabel4.setText("7~11");
        TopBarPanel.add(jLabel4);
        jLabel4.setBounds(300, 20, 59, 47);

        getContentPane().add(TopBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 800, 160));

        CenterPanel.setBackground(new java.awt.Color(253, 253, 242));
        CenterPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CenterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProfileImage.setBackground(new java.awt.Color(255, 255, 255));
        lblProfileImage.setForeground(new java.awt.Color(255, 255, 255));
        lblProfileImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DefaultImage.jpg"))); // NOI18N
        CenterPanel.add(lblProfileImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 100, 100));

        NameLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameLbl.setText("Name:");
        CenterPanel.add(NameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 50, -1));

        IDlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IDlbl.setText("ID:");
        CenterPanel.add(IDlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 50, -1));

        GenderLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GenderLbl.setText("Gender:");
        CenterPanel.add(GenderLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        StatusLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        StatusLbl.setText("Status:");
        CenterPanel.add(StatusLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 50, 20));

        DOBLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DOBLbl.setText("DOB");
        CenterPanel.add(DOBLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 50, -1));

        PersonalDetailsPanel.setBackground(new java.awt.Color(255, 243, 224));
        PersonalDetailsPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PersonalDetailsPanel.setLayout(null);

        PersonalDetails.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        PersonalDetails.setText("Personal Details:");
        PersonalDetailsPanel.add(PersonalDetails);
        PersonalDetails.setBounds(10, 10, 140, 17);

        Address.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/location.png"))); // NOI18N
        PersonalDetailsPanel.add(Address);
        Address.setBounds(10, 30, 24, 30);

        DOB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calendar.png"))); // NOI18N
        PersonalDetailsPanel.add(DOB);
        DOB.setBounds(10, 66, 24, 30);

        Email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mail.png"))); // NOI18N
        PersonalDetailsPanel.add(Email);
        Email.setBounds(240, 40, 24, 24);

        PhoneNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/phone-call.png"))); // NOI18N
        PersonalDetailsPanel.add(PhoneNo);
        PhoneNo.setBounds(240, 66, 24, 30);

        txtAddress.setBackground(new java.awt.Color(255, 243, 224));
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        PersonalDetailsPanel.add(txtAddress);
        txtAddress.setBounds(50, 40, 150, 23);

        txtDob.setBackground(new java.awt.Color(255, 243, 224));
        PersonalDetailsPanel.add(txtDob);
        txtDob.setBounds(50, 70, 150, 23);

        txtEmail.setBackground(new java.awt.Color(255, 243, 224));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        PersonalDetailsPanel.add(txtEmail);
        txtEmail.setBounds(280, 40, 140, 23);

        txtPhoneNumber.setBackground(new java.awt.Color(255, 243, 224));
        PersonalDetailsPanel.add(txtPhoneNumber);
        txtPhoneNumber.setBounds(280, 70, 140, 23);

        CenterPanel.add(PersonalDetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 470, 110));

        JobDetailsPanel.setBackground(new java.awt.Color(255, 243, 224));
        JobDetailsPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Job Details:");
        JobDetailsPanel.add(jLabel1);
        jLabel1.setBounds(10, 0, 170, 30);
        jLabel1.getAccessibleContext().setAccessibleName("JobDetails");

        RoleLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RoleLbl.setText("Role:");
        JobDetailsPanel.add(RoleLbl);
        RoleLbl.setBounds(10, 40, 90, 30);

        WorkLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        WorkLbl.setText("Work Shift:");
        JobDetailsPanel.add(WorkLbl);
        WorkLbl.setBounds(10, 80, 90, 30);

        DepartmentLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DepartmentLbl.setText("Department:");
        JobDetailsPanel.add(DepartmentLbl);
        DepartmentLbl.setBounds(10, 120, 90, 30);

        JoinedLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JoinedLbl.setText("Joined Date:");
        JobDetailsPanel.add(JoinedLbl);
        JoinedLbl.setBounds(10, 160, 90, 30);

        txtRole.setBackground(new java.awt.Color(255, 243, 224));
        JobDetailsPanel.add(txtRole);
        txtRole.setBounds(100, 42, 180, 30);

        txtShift.setBackground(new java.awt.Color(255, 243, 224));
        JobDetailsPanel.add(txtShift);
        txtShift.setBounds(100, 80, 180, 30);

        txtDepartment.setBackground(new java.awt.Color(255, 243, 224));
        JobDetailsPanel.add(txtDepartment);
        txtDepartment.setBounds(100, 120, 180, 30);

        txtJoinedDate.setBackground(new java.awt.Color(255, 243, 224));
        JobDetailsPanel.add(txtJoinedDate);
        txtJoinedDate.setBounds(100, 160, 180, 30);

        CenterPanel.add(JobDetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 290, 280));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        CenterPanel.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 190, -1));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        CenterPanel.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 190, -1));
        CenterPanel.add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 190, -1));
        CenterPanel.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 190, -1));
        CenterPanel.add(txtDOBdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 190, -1));

        btnDelete.setBackground(new java.awt.Color(255, 243, 224));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CenterPanel.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 120, 50));

        btnAdd.setBackground(new java.awt.Color(255, 243, 224));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CenterPanel.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 120, 50));

        btnEdit.setBackground(new java.awt.Color(255, 243, 224));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CenterPanel.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 120, 50));

        btnSearch.setBackground(new java.awt.Color(255, 243, 224));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CenterPanel.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 120, 50));

        btnBrowseImage.setBackground(new java.awt.Color(255, 243, 224));
        btnBrowseImage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBrowseImage.setText("Select Image");
        btnBrowseImage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBrowseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseImageActionPerformed(evt);
            }
        });
        CenterPanel.add(btnBrowseImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 120, 50));

        getContentPane().add(CenterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 800, 440));

        SidePanel2.setBackground(new java.awt.Color(255, 243, 224));
        SidePanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SidePanel2.setLayout(null);

        Logo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Screenshot_2025-05-22_222007-removebg-preview (1).png"))); // NOI18N
        Logo3.setText("jLabel1");
        SidePanel2.add(Logo3);
        Logo3.setBounds(30, 0, 136, 110);

        DashboardBtn.setBackground(new java.awt.Color(255, 243, 224));
        DashboardBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DashboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dashboard.png"))); // NOI18N
        DashboardBtn.setText("Dashboard");
        DashboardBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DashboardBtn.setIconTextGap(10);
        SidePanel2.add(DashboardBtn);
        DashboardBtn.setBounds(20, 190, 160, 40);

        OrderButton2.setBackground(new java.awt.Color(255, 243, 224));
        OrderButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OrderButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order.png"))); // NOI18N
        OrderButton2.setText("Order");
        OrderButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OrderButton2.setIconTextGap(10);
        OrderButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderButton2ActionPerformed(evt);
            }
        });
        SidePanel2.add(OrderButton2);
        OrderButton2.setBounds(20, 390, 160, 40);

        BillButton2.setBackground(new java.awt.Color(255, 243, 224));
        BillButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BillButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order.png"))); // NOI18N
        BillButton2.setText("Bill");
        BillButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BillButton2.setIconTextGap(10);
        SidePanel2.add(BillButton2);
        BillButton2.setBounds(20, 440, 160, 40);

        LogoutButton2.setBackground(new java.awt.Color(255, 243, 224));
        LogoutButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogoutButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        LogoutButton2.setText("Logout");
        LogoutButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogoutButton2.setIconTextGap(10);
        SidePanel2.add(LogoutButton2);
        LogoutButton2.setBounds(20, 540, 160, 40);

        Slogan2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Slogan2.setText("7 people serving since 11 AM");
        Slogan2.setToolTipText("");
        SidePanel2.add(Slogan2);
        Slogan2.setBounds(10, 100, 180, 20);

        reservationbtn1.setBackground(new java.awt.Color(255, 243, 224));
        reservationbtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reservationbtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order.png"))); // NOI18N
        reservationbtn1.setText("Reservation");
        reservationbtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reservationbtn1.setIconTextGap(10);
        SidePanel2.add(reservationbtn1);
        reservationbtn1.setBounds(20, 240, 160, 40);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        SidePanel2.add(jSeparator5);
        jSeparator5.setBounds(0, 120, 200, 20);

        eventbtn1.setBackground(new java.awt.Color(255, 243, 224));
        eventbtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eventbtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order.png"))); // NOI18N
        eventbtn1.setText("Event Booking");
        eventbtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eventbtn1.setIconTextGap(10);
        SidePanel2.add(eventbtn1);
        eventbtn1.setBounds(20, 290, 160, 40);

        reservationbtn4.setBackground(new java.awt.Color(255, 243, 224));
        reservationbtn4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reservationbtn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order.png"))); // NOI18N
        reservationbtn4.setText("Reservation");
        reservationbtn4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reservationbtn4.setIconTextGap(10);
        SidePanel2.add(reservationbtn4);
        reservationbtn4.setBounds(20, 240, 160, 40);

        Menubtn4.setBackground(new java.awt.Color(255, 243, 224));
        Menubtn4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Menubtn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order.png"))); // NOI18N
        Menubtn4.setText("Manage Menu");
        Menubtn4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Menubtn4.setIconTextGap(10);
        SidePanel2.add(Menubtn4);
        Menubtn4.setBounds(20, 340, 160, 40);

        getContentPane().add(SidePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        SidePanel3.setBackground(new java.awt.Color(255, 243, 224));
        SidePanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SidePanel3.setLayout(null);

        Logo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Screenshot_2025-05-22_222007-removebg-preview (1).png"))); // NOI18N
        Logo4.setText("jLabel1");
        SidePanel3.add(Logo4);
        Logo4.setBounds(30, 0, 136, 110);

        DashboardBtn1.setBackground(new java.awt.Color(255, 243, 224));
        DashboardBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DashboardBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dashboard.png"))); // NOI18N
        DashboardBtn1.setText("Dashboard");
        DashboardBtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DashboardBtn1.setIconTextGap(10);
        SidePanel3.add(DashboardBtn1);
        DashboardBtn1.setBounds(20, 190, 160, 40);

        LogoutButton3.setBackground(new java.awt.Color(255, 243, 224));
        LogoutButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogoutButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        LogoutButton3.setText("Logout");
        LogoutButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogoutButton3.setIconTextGap(10);
        SidePanel3.add(LogoutButton3);
        LogoutButton3.setBounds(20, 540, 160, 40);

        Slogan3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Slogan3.setText("7 people serving since 11 AM");
        Slogan3.setToolTipText("");
        SidePanel3.add(Slogan3);
        Slogan3.setBounds(10, 100, 180, 20);

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        SidePanel3.add(jSeparator6);
        jSeparator6.setBounds(0, 120, 200, 20);

        employeebtn.setBackground(new java.awt.Color(255, 243, 224));
        employeebtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        employeebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/employee.png"))); // NOI18N
        employeebtn.setText("Manage Employee");
        employeebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        employeebtn.setIconTextGap(10);
        SidePanel3.add(employeebtn);
        employeebtn.setBounds(20, 250, 160, 40);

        getContentPane().add(SidePanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void btnBrowseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBrowseImageActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void OrderButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDetailView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JButton BillButton2;
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JLabel DOB;
    private javax.swing.JLabel DOBLbl;
    private javax.swing.JButton DashboardBtn;
    private javax.swing.JButton DashboardBtn1;
    private javax.swing.JLabel DepartmentLbl;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel GenderLbl;
    private javax.swing.JLabel IDlbl;
    private javax.swing.JPanel JobDetailsPanel;
    private javax.swing.JLabel JoinedLbl;
    private javax.swing.JLabel Logo3;
    private javax.swing.JLabel Logo4;
    private javax.swing.JButton LogoutButton2;
    private javax.swing.JButton LogoutButton3;
    private javax.swing.JButton Menubtn4;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JButton OrderButton2;
    private javax.swing.JLabel PersonalDetails;
    private javax.swing.JPanel PersonalDetailsPanel;
    private javax.swing.JLabel PhoneNo;
    private javax.swing.JLabel RoleLbl;
    private javax.swing.JPanel SidePanel2;
    private javax.swing.JPanel SidePanel3;
    private javax.swing.JLabel Slogan2;
    private javax.swing.JLabel Slogan3;
    private javax.swing.JLabel StatusLbl;
    private javax.swing.JPanel TopBarPanel;
    private javax.swing.JLabel WorkLbl;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBrowseImage;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton employeebtn;
    private javax.swing.JButton eventbtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblProfileImage;
    private javax.swing.JButton reservationbtn1;
    private javax.swing.JButton reservationbtn4;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDOBdate;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtJoinedDate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtShift;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables

public JTextField getTxtID() {
    return txtID;
}
public JTextField getTxtName() {
    return txtName; 
}
public JTextField getTxtGender() { 
    return txtGender; 
}
public JTextField getTxtStatus() { 
    return txtStatus; 
}
public JTextField getTxtDOBdate() { 
    return txtDOBdate; 
}
public JTextField getTxtRole() { 
    return txtRole; }
public JTextField getTxtShift() { return txtShift; 
}
public JTextField getTxtDepartment() { 
    return txtDepartment; 
}
public JTextField getTxtJoinedDate() { 
    return txtJoinedDate; 
}
public JTextField getTxtAddress() { 
    return txtAddress; 
}
public JTextField getTxtEmail() { 
    return txtEmail; 
}
public JTextField getTxtPhoneNumber() {
    return txtPhoneNumber; }

public JLabel getLblProfileImage() { 
    return lblProfileImage; 
}

public void addAdminDashboardListener(ActionListener listener){
    DashboardBtn1.addActionListener(listener);
}
public void addEmployeeDetailListener(ActionListener listener){
    employeebtn.addActionListener(listener);
}
public void addLogoutListener(ActionListener listener){
    LogoutButton2.addActionListener(listener);
    LogoutButton3.addActionListener(listener);
}
}
