
package View;

import Controller.MenuController;
import Dao.MenuDAO;
import Model.MenuItemModel;
import java.awt.event.ActionListener;
import javax.swing.JButton;

import javax.swing.JOptionPane;

public class ManageMenu extends javax.swing.JFrame {

    public ManageMenu() {
        initComponents();
        MenuController controller = new MenuController(this);
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanel2 = new javax.swing.JPanel();
        Logo3 = new javax.swing.JLabel();
        DashboardBtn = new javax.swing.JButton();
        OrderButton2 = new javax.swing.JButton();
        BillButton2 = new javax.swing.JButton();
        LogoutButton2 = new javax.swing.JButton();
        Slogan2 = new javax.swing.JLabel();
        reservationbtn1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        eventbtn1 = new javax.swing.JButton();
        reservationbtn4 = new javax.swing.JButton();
        Menubtn4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        createMenuBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jitemname = new javax.swing.JLabel();
        jnoofitem = new javax.swing.JLabel();
        jpriceofitem = new javax.swing.JLabel();
        jemployeename = new javax.swing.JLabel();
        itemNameField = new javax.swing.JTextField();
        quantityField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        EmployeeNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SidePanel2.setBackground(new java.awt.Color(255, 243, 224));
        SidePanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SidePanel2.setLayout(null);

        Logo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Screenshot_2025-05-22_222007-removebg-preview (1).png"))); // NOI18N
        Logo3.setText("jLabel1");
        SidePanel2.add(Logo3);
        Logo3.setBounds(30, 0, 136, 110);

        DashboardBtn.setBackground(new java.awt.Color(255, 243, 224));
        DashboardBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DashboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dashboard.png"))); // NOI18N
        DashboardBtn.setText("Dashboard");
        DashboardBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DashboardBtn.setIconTextGap(10);
        SidePanel2.add(DashboardBtn);
        DashboardBtn.setBounds(20, 190, 160, 40);

        OrderButton2.setBackground(new java.awt.Color(255, 243, 224));
        OrderButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OrderButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order.png"))); // NOI18N
        OrderButton2.setText("Order");
        OrderButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OrderButton2.setIconTextGap(10);
        OrderButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderButton2ActionPerformed(evt);
            }
        });
        SidePanel2.add(OrderButton2);
        OrderButton2.setBounds(20, 390, 160, 40);

        BillButton2.setBackground(new java.awt.Color(255, 243, 224));
        BillButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BillButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order.png"))); // NOI18N
        BillButton2.setText("Bill");
        BillButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BillButton2.setIconTextGap(10);
        SidePanel2.add(BillButton2);
        BillButton2.setBounds(20, 440, 160, 40);

        LogoutButton2.setBackground(new java.awt.Color(255, 243, 224));
        LogoutButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogoutButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        LogoutButton2.setText("Logout");
        LogoutButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogoutButton2.setIconTextGap(10);
        SidePanel2.add(LogoutButton2);
        LogoutButton2.setBounds(20, 540, 160, 40);

        Slogan2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Slogan2.setText("7 people serving since 11 AM");
        Slogan2.setToolTipText("");
        SidePanel2.add(Slogan2);
        Slogan2.setBounds(10, 100, 180, 20);

        reservationbtn1.setBackground(new java.awt.Color(255, 243, 224));
        reservationbtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reservationbtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order.png"))); // NOI18N
        reservationbtn1.setText("Reservation");
        reservationbtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reservationbtn1.setIconTextGap(10);
        SidePanel2.add(reservationbtn1);
        reservationbtn1.setBounds(20, 240, 160, 40);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        SidePanel2.add(jSeparator5);
        jSeparator5.setBounds(0, 120, 200, 20);

        eventbtn1.setBackground(new java.awt.Color(255, 243, 224));
        eventbtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eventbtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order.png"))); // NOI18N
        eventbtn1.setText("Event Booking");
        eventbtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eventbtn1.setIconTextGap(10);
        SidePanel2.add(eventbtn1);
        eventbtn1.setBounds(20, 290, 160, 40);

        reservationbtn4.setBackground(new java.awt.Color(255, 243, 224));
        reservationbtn4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reservationbtn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order.png"))); // NOI18N
        reservationbtn4.setText("Reservation");
        reservationbtn4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reservationbtn4.setIconTextGap(10);
        SidePanel2.add(reservationbtn4);
        reservationbtn4.setBounds(20, 240, 160, 40);

        Menubtn4.setBackground(new java.awt.Color(255, 243, 224));
        Menubtn4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Menubtn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order.png"))); // NOI18N
        Menubtn4.setText("Manage Menu");
        Menubtn4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Menubtn4.setIconTextGap(10);
        SidePanel2.add(Menubtn4);
        Menubtn4.setBounds(20, 340, 160, 40);

        jPanel1.setBackground(new java.awt.Color(253, 253, 242));

        jPanel6.setBackground(new java.awt.Color(253, 253, 242));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        createMenuBtn.setBackground(new java.awt.Color(201, 182, 153));
        createMenuBtn.setText("Create Menu");
        createMenuBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMenuBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(201, 182, 153));
        deleteBtn.setText("Delete Menu");
        deleteBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jitemname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jitemname.setText("Item Name");

        jnoofitem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jnoofitem.setText("No.Of Item");

        jpriceofitem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jpriceofitem.setText("Price of Item");

        jemployeename.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jemployeename.setText("Employee name");

        itemNameField.setBackground(new java.awt.Color(201, 182, 153));
        itemNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNameFieldActionPerformed(evt);
            }
        });

        quantityField.setBackground(new java.awt.Color(201, 182, 153));

        priceField.setBackground(new java.awt.Color(201, 182, 153));

        EmployeeNameField.setBackground(new java.awt.Color(201, 182, 153));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(createMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jitemname)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jnoofitem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jpriceofitem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap(11, Short.MAX_VALUE)
                        .addComponent(jemployeename)
                        .addGap(205, 205, 205)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(itemNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addComponent(quantityField, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(EmployeeNameField, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(priceField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jitemname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jnoofitem, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpriceofitem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jemployeename, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("The Menu Behind the Magic");

        jLabel4.setFont(new java.awt.Font("Jaini Purva", 3, 36)); // NOI18N
        jLabel4.setText("7~11");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(290, 290, 290)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(312, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(528, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SidePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SidePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OrderButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderButton2ActionPerformed

    private void createMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMenuBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createMenuBtnActionPerformed

    private void itemNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameFieldActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BillButton2;
    private javax.swing.JButton DashboardBtn;
    private javax.swing.JTextField EmployeeNameField;
    private javax.swing.JLabel Logo3;
    private javax.swing.JButton LogoutButton2;
    private javax.swing.JButton Menubtn4;
    private javax.swing.JButton OrderButton2;
    private javax.swing.JPanel SidePanel2;
    private javax.swing.JLabel Slogan2;
    private javax.swing.JButton createMenuBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton eventbtn1;
    private javax.swing.JTextField itemNameField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel jemployeename;
    private javax.swing.JLabel jitemname;
    private javax.swing.JLabel jnoofitem;
    private javax.swing.JLabel jpriceofitem;
    private javax.swing.JTextField priceField;
    private javax.swing.JTextField quantityField;
    private javax.swing.JButton reservationbtn1;
    private javax.swing.JButton reservationbtn4;
    // End of variables declaration//GEN-END:variables

public void addCreateListerner(ActionListener listener){
    createMenuBtn.addActionListener(listener);
}

public void addDeleteListerner(ActionListener listener){
    deleteBtn.addActionListener(listener);
}

public void addMenuListener(ActionListener listener) {
        Menubtn4.addActionListener(listener);
    }
   public void addLogoutListener(ActionListener listener) {
    LogoutButton2.addActionListener(listener);
}

public void addDashboardListener(ActionListener listener){
    DashboardBtn.addActionListener(listener); 
}
public void addBillListener(ActionListener listener){
    BillButton2.addActionListener(listener);
}
public void addReservationListener(ActionListener listener){
    reservationbtn1.addActionListener(listener);
}
public void addEventListener(ActionListener listener){
    eventbtn1.addActionListener(listener);
}

public javax.swing.JTextField getItemNameField() {
    return itemNameField;
}

public javax.swing.JTextField getNoOfItemField() {
    return quantityField;
}

public javax.swing.JTextField getPriceField() {
    return priceField;
}

public javax.swing.JTextField getEmployeeNameField() {
    return EmployeeNameField;
}
}

