/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.EDashboardController;
import java.awt.event.ActionListener;

/**
 *
 * @author uttu
 */
public class Reservation extends javax.swing.JFrame {

    /**
     * Creates new form BookingEvents
     */
    public Reservation() {
        initComponents();
//        EDashboardController controller = new EDashboardController();
//        controller.setupLogoutListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DashboardCenterPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        SidePanel = new javax.swing.JPanel();
        Logo1 = new javax.swing.JLabel();
        DashboardButton = new javax.swing.JButton();
        OrderButton = new javax.swing.JButton();
        BillButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        Slogan = new javax.swing.JLabel();
        Eventsbtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        Menubtn2 = new javax.swing.JButton();
        Reservationbtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DashboardCenterPanel.setBackground(new java.awt.Color(253, 253, 242));
        DashboardCenterPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DashboardCenterPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Jaini Purva", 3, 48)); // NOI18N
        jLabel1.setText("7 ~ 11");
        DashboardCenterPanel.add(jLabel1);
        jLabel1.setBounds(300, 20, 100, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Book the Moment. Leave the Magic to Us");
        DashboardCenterPanel.add(jLabel2);
        jLabel2.setBounds(130, 70, 460, 50);
        DashboardCenterPanel.add(jSeparator4);
        jSeparator4.setBounds(30, 350, 670, 10);
        DashboardCenterPanel.add(jLabel4);
        jLabel4.setBounds(660, 10, 30, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Staff on Duty");
        DashboardCenterPanel.add(jLabel3);
        jLabel3.setBounds(30, 360, 170, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Floor 1");
        DashboardCenterPanel.add(jLabel5);
        jLabel5.setBounds(50, 180, 80, 29);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Floor 2");
        DashboardCenterPanel.add(jLabel6);
        jLabel6.setBounds(290, 180, 80, 29);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Floor 3");
        DashboardCenterPanel.add(jLabel7);
        jLabel7.setBounds(520, 180, 80, 29);

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setText("1");
        DashboardCenterPanel.add(jLabel8);
        jLabel8.setBounds(30, 230, 20, 30);

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel9.setText("2");
        DashboardCenterPanel.add(jLabel9);
        jLabel9.setBounds(280, 230, 10, 30);

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel10.setText("3");
        DashboardCenterPanel.add(jLabel10);
        jLabel10.setBounds(510, 230, 10, 20);

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel11.setText("4");
        DashboardCenterPanel.add(jLabel11);
        jLabel11.setBounds(30, 280, 10, 17);

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel12.setText("7");
        DashboardCenterPanel.add(jLabel12);
        jLabel12.setBounds(30, 320, 10, 17);

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel13.setText("5");
        DashboardCenterPanel.add(jLabel13);
        jLabel13.setBounds(280, 280, 10, 17);

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel14.setText("8");
        DashboardCenterPanel.add(jLabel14);
        jLabel14.setBounds(280, 320, 10, 20);

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel15.setText("6");
        DashboardCenterPanel.add(jLabel15);
        jLabel15.setBounds(510, 280, 10, 17);

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel16.setText("9");
        DashboardCenterPanel.add(jLabel16);
        jLabel16.setBounds(510, 320, 10, 17);
        DashboardCenterPanel.add(jLabel17);
        jLabel17.setBounds(80, 230, 120, 30);

        jLabel18.setText("jLabel18");
        DashboardCenterPanel.add(jLabel18);
        jLabel18.setBounds(80, 280, 49, 17);

        jLabel19.setText("jLabel19");
        DashboardCenterPanel.add(jLabel19);
        jLabel19.setBounds(80, 320, 49, 17);

        jLabel20.setText("jLabel20");
        DashboardCenterPanel.add(jLabel20);
        jLabel20.setBounds(330, 230, 49, 20);

        jLabel21.setText("jLabel21");
        DashboardCenterPanel.add(jLabel21);
        jLabel21.setBounds(330, 280, 49, 17);

        jLabel22.setText("jLabel22");
        DashboardCenterPanel.add(jLabel22);
        jLabel22.setBounds(330, 320, 49, 17);

        jLabel23.setText("jLabel23");
        DashboardCenterPanel.add(jLabel23);
        jLabel23.setBounds(560, 230, 49, 17);

        jLabel24.setText("jLabel24");
        DashboardCenterPanel.add(jLabel24);
        jLabel24.setBounds(560, 280, 49, 17);

        jLabel25.setText("jLabel25");
        DashboardCenterPanel.add(jLabel25);
        jLabel25.setBounds(560, 320, 49, 17);
        DashboardCenterPanel.add(jSeparator5);
        jSeparator5.setBounds(30, 160, 660, 10);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel26.setText("Room Status by Floor");
        DashboardCenterPanel.add(jLabel26);
        jLabel26.setBounds(30, 130, 170, 17);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Floors", "Assigned Staff", "Date"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        DashboardCenterPanel.add(jScrollPane2);
        jScrollPane2.setBounds(100, 410, 390, 180);

        SidePanel.setBackground(new java.awt.Color(255, 243, 224));
        SidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SidePanel.setLayout(null);

        Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        SidePanel.add(Logo1);
        Logo1.setBounds(30, 10, 136, 110);

        DashboardButton.setBackground(new java.awt.Color(255, 243, 224));
        DashboardButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DashboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dashboard.png"))); // NOI18N
        DashboardButton.setText("Dashboard");
        DashboardButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DashboardButton.setIconTextGap(10);
        DashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardButtonActionPerformed(evt);
            }
        });
        SidePanel.add(DashboardButton);
        DashboardButton.setBounds(20, 190, 160, 40);

        OrderButton.setBackground(new java.awt.Color(255, 243, 224));
        OrderButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OrderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order.png"))); // NOI18N
        OrderButton.setText("Order");
        OrderButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OrderButton.setIconTextGap(10);
        OrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderButtonActionPerformed(evt);
            }
        });
        SidePanel.add(OrderButton);
        OrderButton.setBounds(20, 390, 160, 40);

        BillButton.setBackground(new java.awt.Color(255, 243, 224));
        BillButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BillButton.setText("Bill");
        BillButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BillButton.setIconTextGap(10);
        BillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillButtonActionPerformed(evt);
            }
        });
        SidePanel.add(BillButton);
        BillButton.setBounds(20, 440, 160, 40);

        LogoutButton.setBackground(new java.awt.Color(255, 243, 224));
        LogoutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogoutButton.setIconTextGap(10);
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        SidePanel.add(LogoutButton);
        LogoutButton.setBounds(20, 540, 160, 40);

        Slogan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Slogan.setText("7 people serving since 11 AM");
        Slogan.setToolTipText("");
        SidePanel.add(Slogan);
        Slogan.setBounds(10, 110, 180, 20);

        Eventsbtn.setBackground(new java.awt.Color(255, 243, 224));
        Eventsbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Eventsbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order.png"))); // NOI18N
        Eventsbtn.setText("Event Manage");
        Eventsbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Eventsbtn.setIconTextGap(10);
        SidePanel.add(Eventsbtn);
        Eventsbtn.setBounds(20, 290, 160, 40);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        SidePanel.add(jSeparator3);
        jSeparator3.setBounds(0, 130, 200, 10);

        Menubtn2.setBackground(new java.awt.Color(255, 243, 224));
        Menubtn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Menubtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order.png"))); // NOI18N
        Menubtn2.setText("Manage Menu");
        Menubtn2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Menubtn2.setIconTextGap(10);
        SidePanel.add(Menubtn2);
        Menubtn2.setBounds(20, 340, 160, 40);

        Reservationbtn1.setBackground(new java.awt.Color(255, 243, 224));
        Reservationbtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Reservationbtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order.png"))); // NOI18N
        Reservationbtn1.setText("Reservation");
        Reservationbtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Reservationbtn1.setIconTextGap(10);
        SidePanel.add(Reservationbtn1);
        Reservationbtn1.setBounds(20, 240, 160, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DashboardCenterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DashboardCenterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(SidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DashboardButtonActionPerformed

    private void OrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderButtonActionPerformed

    private void BillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BillButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BillButton;
    private javax.swing.JButton DashboardButton;
    private javax.swing.JPanel DashboardCenterPanel;
    private javax.swing.JButton Eventsbtn;
    private javax.swing.JLabel Logo1;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton Menubtn2;
    private javax.swing.JButton OrderButton;
    private javax.swing.JButton Reservationbtn1;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JLabel Slogan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

public void addDashboardListener(ActionListener listener) {
        DashboardButton.addActionListener(listener);
    }
public void addReservationListener(ActionListener listener) {
        Reservationbtn1.addActionListener(listener);
    }
public void addEventListener(ActionListener listener) {
        Eventsbtn.addActionListener(listener);
    }
public void addMenuListener(ActionListener listener) {
        Menubtn2.addActionListener(listener);
    }
public void addOrderListener(ActionListener listener) {
        OrderButton.addActionListener(listener);
    }
public void addBillListener(ActionListener listener) {
        BillButton.addActionListener(listener);
    }
public void addLogoutListener(ActionListener listener) {
        LogoutButton.addActionListener(listener);
    }
}
