
package View;
import Controller.SignInController;
import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JTextField;

public class SignIn extends javax.swing.JFrame {
    private JTextField passwordField = new JTextField();
    public JTextField getPasswordField(){
        return jPass;
    }

    public SignIn() {
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jColorChooser3 = new javax.swing.JColorChooser();
        label1 = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Bsignin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BForgetPass = new javax.swing.JButton();
        Bsignup = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPass = new javax.swing.JTextField();
        jEmail1 = new javax.swing.JTextField();
        EmployeeSigninbtn = new javax.swing.JButton();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 228, 201));
        setBounds(new java.awt.Rectangle(255, 228, 201, 201));

        jPanel1.setBackground(new java.awt.Color(255, 228, 201));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        jLabel5.setText("Don’t have an account ?");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel1.setText("The only thing faster than our login? Your success");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel2.setText("Missed us, didn’t you?");

        Bsignin.setBackground(new java.awt.Color(78, 31, 0));
        Bsignin.setForeground(new java.awt.Color(255, 228, 201));
        Bsignin.setText("SIGN IN");
        Bsignin.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                BsigninComponentMoved(evt);
            }
        });
        Bsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsigninActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Jaini Purva", 1, 36)); // NOI18N
        jLabel4.setText("7 ~ 11");

        BForgetPass.setBackground(new java.awt.Color(255, 228, 201));
        BForgetPass.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        BForgetPass.setText("Forget Password?");
        BForgetPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BForgetPassActionPerformed(evt);
            }
        });

        Bsignup.setBackground(new java.awt.Color(255, 228, 201));
        Bsignup.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        Bsignup.setText("SignUp");
        Bsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsignupActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Screenshot 2025-05-21 at 18.17.25.png"))); // NOI18N

        jPass.setBackground(new java.awt.Color(255, 228, 201));
        jPass.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jPass.setText("Password");
        jPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPassFocusLost(evt);
            }
        });
        jPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassActionPerformed(evt);
            }
        });

        jEmail1.setBackground(new java.awt.Color(255, 228, 201));
        jEmail1.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jEmail1.setText("Email");
        jEmail1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jEmail1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jEmail1FocusLost(evt);
            }
        });
        jEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmail1ActionPerformed(evt);
            }
        });

        EmployeeSigninbtn.setBackground(new java.awt.Color(78, 31, 0));
        EmployeeSigninbtn.setForeground(new java.awt.Color(255, 228, 201));
        EmployeeSigninbtn.setText("Employee Login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPass, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BForgetPass, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(EmployeeSigninbtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bsignup)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel6)
                .addGap(37, 37, 37)
                .addComponent(jLabel10)
                .addGap(190, 190, 190))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(jEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(597, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(74, 74, 74)
                .addComponent(jPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BForgetPass, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Bsignin)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bsignup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmployeeSigninbtn)
                .addGap(10, 10, 10))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(157, 157, 157)
                    .addComponent(jEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(175, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsigninActionPerformed
//         Bsignin.addActionListener(new SignInController().new AddUserListener());
    }//GEN-LAST:event_BsigninActionPerformed

    private void BsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsignupActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BsignupActionPerformed

    private void BsigninComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BsigninComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_BsigninComponentMoved

    private void BForgetPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BForgetPassActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_BForgetPassActionPerformed

    private void jPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPassFocusGained
        // TODO add your handling code here:
        if (jPass.getText().equals("Password")){
            jPass.setText("");
            jPass.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jPassFocusGained

    private void jPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPassFocusLost
        // TODO add your handling code here:
        if (jPass.getText().isEmpty()){
            jPass.setText("Password");
            jPass.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jPassFocusLost

    private void jPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassActionPerformed

    private void jEmail1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jEmail1FocusGained
        // TODO add your handling code here:
            if (jEmail1.getText().equals("Email")){
            jEmail1.setText("");
            jEmail1.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_jEmail1FocusGained

    private void jEmail1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jEmail1FocusLost
        // TODO add your handling code here:
        if (jEmail1.getText().isEmpty()){
            jEmail1.setText("Email");
            jEmail1.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jEmail1FocusLost

    private void jEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmail1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BForgetPass;
    private javax.swing.JButton Bsignin;
    private javax.swing.JButton Bsignup;
    private javax.swing.JButton EmployeeSigninbtn;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JColorChooser jColorChooser3;
    private javax.swing.JTextField jEmail1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPass;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables

 public void addLoginUserListener(ActionListener listener) {
        Bsignin.addActionListener(listener);
    }
 
  public void addRegisterListener(ActionListener listener) {
        Bsignup.addActionListener(listener);
    }
  
  public void addForgotListener(ActionListener listener){
      BForgetPass.addActionListener(listener);
  }
  public void addELoginListener(ActionListener listener){
      EmployeeSigninbtn.addActionListener(listener);
  } 
    /**
     * @return the emailField
     */
    public javax.swing.JTextField getEmailField() {
        return jEmail1;
    }




}
